/*******************************************************************************
* FILE NAME: DiveDemo2.h                                                       *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     DiveDemo2                                                                *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_DiveDemo2
#define WND_DiveDemo2  VBBASEWINDOWID
#endif

#define WNDOFFSET_DiveDemo2_FrameWindow  0
#define WND_DiveDemo2_FrameWindow  WND_DiveDemo2

#define WNDOFFSET_DiveDemo2_InfoArea1  1
#define WND_DiveDemo2_InfoArea1  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_InfoArea1

#define WNDOFFSET_DiveDemo2_ToolBar1  2
#define WND_DiveDemo2_ToolBar1  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_ToolBar1

#define WNDOFFSET_DiveDemo2_ToolBarButton1  3
#define WND_DiveDemo2_ToolBarButton1  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_ToolBarButton1
#define STRRC_DiveDemo2_ToolBarButton1_avlFlyOverLongText  WND_DiveDemo2_ToolBarButton1 + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_DiveDemo2_ToolBarButton2  4
#define WND_DiveDemo2_ToolBarButton2  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_ToolBarButton2
#define STRRC_DiveDemo2_ToolBarButton2_avlFlyOverLongText  WND_DiveDemo2_ToolBarButton2 + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_DiveDemo2_ToolBarButton3  5
#define WND_DiveDemo2_ToolBarButton3  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_ToolBarButton3
#define STRRC_DiveDemo2_ToolBarButton3_avlFlyOverLongText  WND_DiveDemo2_ToolBarButton3 + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_DiveDemo2_ToolBarButton4  6
#define WND_DiveDemo2_ToolBarButton4  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_ToolBarButton4
#define STRRC_DiveDemo2_ToolBarButton4_avlFlyOverLongText  WND_DiveDemo2_ToolBarButton4 + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_DiveDemo2_ToolBarButton5  7
#define WND_DiveDemo2_ToolBarButton5  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_ToolBarButton5
#define STRRC_DiveDemo2_ToolBarButton5_avlFlyOverLongText  WND_DiveDemo2_ToolBarButton5 + VBLONGFLYTEXTOFFSET

#define WND_DiveDemo2_MultiCellCanvas1  IC_FRAME_CLIENT_ID

#define WNDOFFSET_DiveDemo2_ActualRateProgressIndicator  8
#define WND_DiveDemo2_ActualRateProgressIndicator  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_ActualRateProgressIndicator
#define STRRC_DiveDemo2_ActualRateProgressIndicator_avlFlyOverLongText  WND_DiveDemo2_ActualRateProgressIndicator + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_DiveDemo2_RequestedRateSlider  9
#define WND_DiveDemo2_RequestedRateSlider  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_RequestedRateSlider
#define STRRC_DiveDemo2_RequestedRateSlider_avlFlyOverLongText  WND_DiveDemo2_RequestedRateSlider + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_DiveDemo2_FastCanvas1  10
#define WND_DiveDemo2_FastCanvas1  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_FastCanvas1
#define STRRC_DiveDemo2_FastCanvas1_avlFlyOverLongText  WND_DiveDemo2_FastCanvas1 + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_DiveDemo2_RequestedAnimationRateStaticText  11
#define WND_DiveDemo2_RequestedAnimationRateStaticText  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_RequestedAnimationRateStaticText

#define WNDOFFSET_DiveDemo2_ActualRateStaticText  12
#define WND_DiveDemo2_ActualRateStaticText  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_ActualRateStaticText

#define WNDOFFSET_DiveDemo2_StaticText1  13
#define WND_DiveDemo2_StaticText1  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_StaticText1

#define WNDOFFSET_DiveDemo2_StaticText2  14
#define WND_DiveDemo2_StaticText2  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_StaticText2

#define WNDOFFSET_DiveDemo2_StaticText3  15
#define WND_DiveDemo2_StaticText3  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_StaticText3

#define WNDOFFSET_DiveDemo2_VBFlyText1  16
#define WND_DiveDemo2_VBFlyText1  WND_DiveDemo2 + WNDOFFSET_DiveDemo2_VBFlyText1




