/*******************************************************************************
* FILE NAME: FaderRenderer.cpp                                                 *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     FaderRenderer- Renderer of animation for Demo 2                          *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _FADERRENDERER_
#include "FaderRenderer.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (FaderRenderer::readyId)
const INotificationId FaderRenderer::readyId = "FaderRenderer::readyId";

//------------------------------------------------------------------------------
// FaderRenderer :: FaderRenderer
//------------------------------------------------------------------------------
#pragma export (FaderRenderer::FaderRenderer())
FaderRenderer::FaderRenderer()
{

   userConstructor();
}     //end constructor


//------------------------------------------------------------------------------
// FaderRenderer :: ~FaderRenderer
//------------------------------------------------------------------------------
#pragma export (FaderRenderer::~FaderRenderer())
FaderRenderer::~FaderRenderer()
{
   userConstructor();

}

//------------------------------------------------------------------------------
// FaderRenderer :: initializePart
//------------------------------------------------------------------------------
#pragma export (FaderRenderer::initializePart())
FaderRenderer & FaderRenderer::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// FaderRenderer :: makeConnections
//------------------------------------------------------------------------------
#pragma export (FaderRenderer::makeConnections())
Boolean FaderRenderer::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "FaderRenderer.cpv"
