/*******************************************************************************
* FILE NAME: FaderRenderer.h                                                   *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     FaderRenderer- Renderer of animation for Demo 2                          *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_FaderRenderer
#define WND_FaderRenderer  VBBASEWINDOWID
#endif


