/*******************************************************************************
* FILE NAME: FaderRenderer.hpp                                                 *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     FaderRenderer- Renderer of animation for Demo 2                          *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _FADERRENDERER_
#define _FADERRENDERER_  

class FaderRenderer;

#ifndef _DIVEIMAGERENDERER_
#include "DiveImageRenderer.hpp"
#endif

#include "os2.h"

#include "FaderRenderer.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for FaderRenderer
//*****************************************************************************
class FaderRenderer : public DiveImageRenderer {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   FaderRenderer();

   virtual  ~FaderRenderer();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual FaderRenderer & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:

#include "FaderRenderer.hpv"
};   //FaderRenderer


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
