/*******************************************************************************
* FILE NAME: StarFieldRenderer.hpp                                             *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     StarFieldRenderer- Renderer of animation for Demo 2                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _STARFIELDRENDERER_
#define _STARFIELDRENDERER_  

class StarFieldRenderer;

#ifndef _DIVEIMAGERENDERER_
#include "DiveImageRenderer.hpp"
#endif

#include "os2.h"

#include "IPoint.hpp"

#include "star.hpp"

#include "StarFieldRenderer.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for StarFieldRenderer
//*****************************************************************************
class StarFieldRenderer : public DiveImageRenderer {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   StarFieldRenderer();

   virtual  ~StarFieldRenderer();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual StarFieldRenderer & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:

#include "StarFieldRenderer.hpv"
};   //StarFieldRenderer


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
