/*******************************************************************************
* FILE NAME: StarFieldRenderer.h                                               *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     StarFieldRenderer- Renderer of animation for Demo 2                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_StarFieldRenderer
#define WND_StarFieldRenderer  VBBASEWINDOWID
#endif


