/*******************************************************************************
* FILE NAME: StarFieldRenderer.cpp                                             *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     StarFieldRenderer- Renderer of animation for Demo 2                      *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _STARFIELDRENDERER_
#include "StarFieldRenderer.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (StarFieldRenderer::readyId)
const INotificationId StarFieldRenderer::readyId = "StarFieldRenderer::readyId";

//------------------------------------------------------------------------------
// StarFieldRenderer :: StarFieldRenderer
//------------------------------------------------------------------------------
#pragma export (StarFieldRenderer::StarFieldRenderer())
StarFieldRenderer::StarFieldRenderer()
{

   userConstructor();
}     //end constructor


//------------------------------------------------------------------------------
// StarFieldRenderer :: ~StarFieldRenderer
//------------------------------------------------------------------------------
#pragma export (StarFieldRenderer::~StarFieldRenderer())
StarFieldRenderer::~StarFieldRenderer()
{
   userDestructor();

}

//------------------------------------------------------------------------------
// StarFieldRenderer :: initializePart
//------------------------------------------------------------------------------
#pragma export (StarFieldRenderer::initializePart())
StarFieldRenderer & StarFieldRenderer::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// StarFieldRenderer :: makeConnections
//------------------------------------------------------------------------------
#pragma export (StarFieldRenderer::makeConnections())
Boolean StarFieldRenderer::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "StarFieldRenderer.cpv"
