/*******************************************************************************
* FILE NAME: vbmain.cpp                                                        *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Main program stub for class:                                               *
*     DiveDemo2                                                                *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _IWINDOW_
#include <iwindow.hpp>
#endif

#ifndef _IAPP_
#include <iapp.hpp>
#endif

#ifndef _IMSGBOX_
#include <imsgbox.hpp>
#endif

#ifndef _DIVEDEMO2_
#include "DiveDemo2.hpp"
#endif

#include <stdlib.h>
#include <stdio.h>
#include <assert.h>

//------------------------------------------------------------------------------
// main
//------------------------------------------------------------------------------
int main(int argc, char ** argv)
{
   assert (setvbuf (stderr, 0, _IOLBF, 0) == 0);
   assert (setvbuf (stdout, 0, _IOLBF, 0) == 0);

   IApplication::current().setArgs(argc, argv);

   DiveDemo2 *iPart;
   IMessageBox::Response resp = IMessageBox::unknown;

   do {
      try {
         iPart = new DiveDemo2();
         iPart->initializePart();
         }
      catch (IException& exc) {
         resp = IMessageBox(IWindow::desktopWindow()).show(
                  exc.text(),
                  IMessageBox::retryCancelButton);
         }
      }
   while (resp == IMessageBox::retry);

   if (resp == IMessageBox::cancel) IApplication::current().exit();

   iPart->setAutoDeleteObject();
   iPart->show();
   IApplication::current().run();
   _dump_allocated(10);
   return 0;
}   //end main

