/*******************************************************************************
* FILE NAME: DiveImageBuffer.cpp                                               *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     DiveImageBuffer- Dive image buffer manager                               *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _DIVEIMAGEBUFFER_
#include "DiveImageBuffer.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (DiveImageBuffer::readyId)
const INotificationId DiveImageBuffer::readyId = "DiveImageBuffer::readyId";

//------------------------------------------------------------------------------
// DiveImageBuffer :: DiveImageBuffer
//------------------------------------------------------------------------------
#pragma export (DiveImageBuffer::DiveImageBuffer())
DiveImageBuffer::DiveImageBuffer()
{

   userConstructor();
}     //end constructor


//------------------------------------------------------------------------------
// DiveImageBuffer :: ~DiveImageBuffer
//------------------------------------------------------------------------------
#pragma export (DiveImageBuffer::~DiveImageBuffer())
DiveImageBuffer::~DiveImageBuffer()
{
   userDestructor();

}

//------------------------------------------------------------------------------
// DiveImageBuffer :: initializePart
//------------------------------------------------------------------------------
#pragma export (DiveImageBuffer::initializePart())
DiveImageBuffer & DiveImageBuffer::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// DiveImageBuffer :: makeConnections
//------------------------------------------------------------------------------
#pragma export (DiveImageBuffer::makeConnections())
Boolean DiveImageBuffer::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "DiveImageBuffer.cpv"
