/*******************************************************************************
* FILE NAME: DiveImageRenderer.h                                               *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     DiveImageRenderer- Renderer of image to buffer                           *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_DiveImageRenderer
#define WND_DiveImageRenderer  VBBASEWINDOWID
#endif


