/*******************************************************************************
* FILE NAME: DiveEventHandler.hpp                                              *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     DiveEventHandler                                                         *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _DIVEEVENTHANDLER_
#define _DIVEEVENTHANDLER_

#include <ihandler.hpp>

class DiveEventHandler;

#include "DiveEventHandler.h"

#include "DiveBlitterHandler.hpp"

/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for DiveEventHandler
//*****************************************************************************
class DiveEventHandler : public IHandler {
#include "DiveEventHandler.hpv" //
};   //DiveEventHandler


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
