/*******************************************************************************
* FILE NAME: DiveBlitterHandler.hpp                                            *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     DiveBlitterHandler- Dive blitter handler                                 *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _DIVEBLITTERHANDLER_
#define _DIVEBLITTERHANDLER_  

class DiveBlitterHandler;

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#include <os2.h>

#include <mmioos2.h>

#include <fourcc.h>

#include <dive.h>

#include <iexcept.hpp>

#include <iwindow.hpp>

#include "DiveBlitterHandler.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for DiveBlitterHandler
//*****************************************************************************
class DiveBlitterHandler : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   DiveBlitterHandler();

   virtual  ~DiveBlitterHandler();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual DiveBlitterHandler & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:

#include "DiveBlitterHandler.hpv"
};   //DiveBlitterHandler


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
