/*******************************************************************************
* FILE NAME: DivePaintHandler.hpp                                              *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     DivePaintHandler                                                         *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _DIVEPAINTHANDLER_
#define _DIVEPAINTHANDLER_

class DivePaintHandler;

#include "DivePaintHandler.h"

#include <ipainhdr.hpp>


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for DivePaintHandler
//*****************************************************************************
class DivePaintHandler : public IPaintHandler {
public:
protected:
private:

#include "DivePaintHandler.hpv"
};   //DivePaintHandler


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
