/*******************************************************************************
* FILE NAME: DiveBlitterHandler.cpp                                            *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     DiveBlitterHandler- Dive blitter handler                                 *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _DIVEBLITTERHANDLER_
#include "DiveBlitterHandler.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (DiveBlitterHandler::readyId)
const INotificationId DiveBlitterHandler::readyId = "DiveBlitterHandler::readyId";

//------------------------------------------------------------------------------
// DiveBlitterHandler :: DiveBlitterHandler
//------------------------------------------------------------------------------
#pragma export (DiveBlitterHandler::DiveBlitterHandler())
DiveBlitterHandler::DiveBlitterHandler()
{

}     //end constructor


//------------------------------------------------------------------------------
// DiveBlitterHandler :: ~DiveBlitterHandler
//------------------------------------------------------------------------------
#pragma export (DiveBlitterHandler::~DiveBlitterHandler())
DiveBlitterHandler::~DiveBlitterHandler()
{

}

//------------------------------------------------------------------------------
// DiveBlitterHandler :: initializePart
//------------------------------------------------------------------------------
#pragma export (DiveBlitterHandler::initializePart())
DiveBlitterHandler & DiveBlitterHandler::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// DiveBlitterHandler :: makeConnections
//------------------------------------------------------------------------------
#pragma export (DiveBlitterHandler::makeConnections())
Boolean DiveBlitterHandler::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "DiveBlitterHandler.cpv"
