/*******************************************************************************
* FILE NAME: DiveImageRenderer.hpp                                             *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     DiveImageRenderer- Renderer of image to buffer                           *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _DIVEIMAGERENDERER_
#define _DIVEIMAGERENDERER_  

class DiveImageRenderer;

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#include <os2.h>

#include "FastCanvas.hpp"

#include "DiveImageRenderer.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for DiveImageRenderer
//*****************************************************************************
class DiveImageRenderer : public IStandardNotifier {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   DiveImageRenderer();

   virtual  ~DiveImageRenderer();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   virtual DiveImageRenderer & initializePart();

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   Boolean makeConnections();

private:

#include "DiveImageRenderer.hpv"
};   //DiveImageRenderer


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
