/*******************************************************************************
* FILE NAME: DiveImageRenderer.cpp                                             *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     DiveImageRenderer- Renderer of image to buffer                           *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _DIVEIMAGERENDERER_
#include "DiveImageRenderer.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (DiveImageRenderer::readyId)
const INotificationId DiveImageRenderer::readyId = "DiveImageRenderer::readyId";

//------------------------------------------------------------------------------
// DiveImageRenderer :: DiveImageRenderer
//------------------------------------------------------------------------------
#pragma export (DiveImageRenderer::DiveImageRenderer())
DiveImageRenderer::DiveImageRenderer()
{

   userConstructor();
}     //end constructor


//------------------------------------------------------------------------------
// DiveImageRenderer :: ~DiveImageRenderer
//------------------------------------------------------------------------------
#pragma export (DiveImageRenderer::~DiveImageRenderer())
DiveImageRenderer::~DiveImageRenderer()
{
   userDestructor();

}

//------------------------------------------------------------------------------
// DiveImageRenderer :: initializePart
//------------------------------------------------------------------------------
#pragma export (DiveImageRenderer::initializePart())
DiveImageRenderer & DiveImageRenderer::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// DiveImageRenderer :: makeConnections
//------------------------------------------------------------------------------
#pragma export (DiveImageRenderer::makeConnections())
Boolean DiveImageRenderer::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "DiveImageRenderer.cpv"
