/*******************************************************************************
* FILE NAME: Timer0.cpp                                                        *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Class implementation of the class:                                         *
*     Timer0- timer0.sys high resolution timer                                 *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _INOTIFEV_
#include <inotifev.hpp>
#endif

#ifndef _IOBSERVR_
#include <iobservr.hpp>
#endif

#ifndef _ISTDNTFY_
#include <istdntfy.hpp>
#endif

#ifndef _TIMER0_
#include "Timer0.hpp"
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef _ITRACE_
#include <itrace.hpp>
#endif


#pragma export (Timer0::readyId)
const INotificationId Timer0::readyId = "Timer0::readyId";

//------------------------------------------------------------------------------
// Timer0 :: Timer0
//------------------------------------------------------------------------------
#pragma export (Timer0::Timer0())
Timer0::Timer0()
{

   userConstructor();
}     //end constructor


//------------------------------------------------------------------------------
// Timer0 :: ~Timer0
//------------------------------------------------------------------------------
#pragma export (Timer0::~Timer0())
Timer0::~Timer0()
{
   userDestructor();

}

//------------------------------------------------------------------------------
// Timer0 :: initializePart
//------------------------------------------------------------------------------
#pragma export (Timer0::initializePart())
Timer0 & Timer0::initializePart()
{
   makeConnections();
   notifyObservers(INotificationEvent(readyId, *this));
   return *this;
}


//------------------------------------------------------------------------------
// Timer0 :: makeConnections
//------------------------------------------------------------------------------
#pragma export (Timer0::makeConnections())
Boolean Timer0::makeConnections()
{
   this->enableNotification();

   return true;
}


#include "Timer0.cpv"
